name: Metrics
on: [push]
jobs:
  Metrics:
    runs-on: ubuntu-latest
    steps:
    - name: News kodeteks
      uses: lowlighter/metrics@latest
      with:
        filename: rss.svg
        token: NOT_NEEDED
        base: ""
        plugin_rss: yes
        plugin_rss_source: https://feeds.feedburner.com/kodeteks
        plugin_rss_limit: 4



