name: Metrics
on:
  schedule:
      - cron: "0 0 * * 0"
  workflow_dispatch:

  
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: News kodeteks
      uses: lowlighter/metrics@latest
      with:
        filename: rss.svg
        token: NOT_NEEDED
        base: ""
        plugin_rss: yes
        plugin_rss_source: https://feeds.feedburner.com/kodeteks
        plugin_rss_limit: 4

    - name: Icons
      uses: lowlighter/metrics@latest
      with:
        filename: topics.svg
        token: NOT_NEEDED
        base: ""
        plugin_topics: yes
        plugin_topics_limit: 0
        plugin_topics_mode: icons
        
    - name : metric terminal
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        user: teranixbq
        template: terminal
        base: header, activity, community, repositories, metadata
        config_timezone: Asia/Jakarta
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_analysis_timeout_repositories: 7.5
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%

