name: Metrics
on:
  schedule:
      - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: News kodeteks
      uses: lowlighter/metrics@latest
      with:
        filename: rss.svg
        token: NOT_NEEDED
        base: ""
        plugin_rss: yes
        plugin_rss_source: https://feeds.feedburner.com/kodeteks
        plugin_rss_limit: 4

    - name: Recent posts with descriptions and cover images
      uses: lowlighter/metrics@latest
      with:
        filename: posts.svg
        token: NOT_NEEDED
        base: ""
        plugin_posts: yes
        plugin_posts_source: dev.to/teranixbq
        plugin_posts_limit: 2
        plugin_posts_descriptions: yes
        plugin_posts_covers: yes
        
    - name : metric terminal
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        template: terminal
        base: header, activity, community, repositories, metadata
        config_timezone: Asia/Jakarta

